### PR TITLE
added show samples argument to rlview

### PR DESCRIPTION
**Pull request by wadaniel**

### CODE REVIEW

**Review by webepasc — CHANGES_REQUESTED** [review]
What about another flag --showErrorbars ?

**Comment by wadaniel** [comment]
yes I can add this, I suggest, --showCI 0.95 with an argument for the confidence interval?
and the CI is computed from the length of the averaging window

**Comment by webepasc** [comment]
Perfect

**Review by webepasc — APPROVED** [review]

**Comment by wadaniel** [comment]
CI added

**Review by SergioMartin86 — APPROVED** [review]

**Pull request merged**
